fix broken sign up
beeminder/BeeSwift pull request #163
Opened 2020-08-23 21:13 UTC by krugerk

replace accesstoken with token (apitoken) and support both authToken and accessToken

2020-08-24 08:51 UTC, krugerk commented on BeeSwift/CurrentUserManager.swift
> +        NotificationCenter.default.post(name: Notification.Name(rawValue: CurrentUserManager.signedInNotificationName), object: self)
After successfully signing UP, what about next signing IN with that data?

The sign in response contains data about default notifications.

2020-08-24 09:12 UTC, krugerk commented on BeeSwift/CurrentUserManager.swift
> +        NotificationCenter.default.post(name: Notification.Name(rawValue: CurrentUserManager.signedInNotificationName), object: self)
or fetching user, rather

2020-08-31 20:51 UTC, andrewpbrett commented
This looks good, but could we use this as a first opportunity to write some failing tests and make them green? Just around the sign up/sign in flow for now.

2020-09-01 05:50 UTC, krugerk commented
> This looks good, but could we use this as a first opportunity to write some failing tests and make them green? Just around the sign up/sign in flow for now. 

Been working on it - putting things in place to mock the server's responses.

2021-01-15 20:33 UTC, andrewpbrett requested changes
This looks good but we'd need to have tests for the various operations that use the API token before it can be merged.

2021-05-24 16:28 UTC, closed without merging