Introduce DueBy Table, with deltas due displayed on a goal's screen
beeminder/BeeSwift pull request #547
Opened 2024-12-10 21:41 UTC by krugerk

## Summary
Includes the due by table in the goal, displaying the deltas on the goal screen, where delta_text was previously displayed.
The user can quickly see, at the goal screen, how many of a thing to do to obtain a number of days of safety.

*For UI changes including screenshots of before and after is great.*
![due by deltas](https://github.com/user-attachments/assets/3900e32a-d902-4b95-873a-09b91973e0ed)

## Validation
built and ran the app in the simulator
viewed the goal screen of various goals

Relates to #209 
This shows the deltas on the goal screen. It does not display the entire table and it does not show the totals nor does it show the dates. It restores "amounts to do" previously provided by "delta text". (See #455)

2024-12-10 21:43 UTC, krugerk commented on BeeKit/Model/Goal.swift
> +            print("Error encoding dictionary: \(error)")
logging instead of mere printing

2024-12-10 21:48 UTC, krugerk commented on BeeSwift/GoalViewController.swift
> +            .map { $0 == "✔" ? "✓" : $0 }
preferring this other checkmark, which shows up well on both light and dark

It is also the same used to indicate a goal has data for the day, today (when "todayta" is true, see https://github.com/beeminder/BeeSwift/blob/745cf9875ed6b0303c46d5d8e4c0a2d44796040d/BeeSwift/GoalCollectionViewCell.swift#L27)

2024-12-20 05:44 UTC, dreeves commented
I don't love the aesthetics of this. Maybe also in terms of user-experience, it's cluttery and overwhelming and opaque.

2024-12-22 10:38 UTC, krugerk commented
> I don't love the aesthetics of this. Maybe also in terms of user-experience, it's cluttery and overwhelming and opaque.

The expectation is that the goal screen contains an expandable section, maybe just a label "due by table" where upon tapping it, it expands to show the full table? It seems you may have suggested as much previously https://github.com/beeminder/BeeSwift/issues/36#issuecomment-627741771 .

2025-01-07 05:21 UTC, theospears commented on BeeKit/Model/Goal.swift
> +    }
Can we not use a [ValueTransformer](UICollectionViewDiffableDataSource) to avoid maintaining both properties?

2025-01-07 11:23 UTC, krugerk commented on BeeKit/Model/Goal.swift
> +    }
I think you meant to link to something else with the ValueTransformer link there. I wanted to avoid making a separate core data entity for the due by table. I can look into the value transformer.

2025-01-08 01:46 UTC, theospears commented
Sharing my higher level thoughts here
* We clearly need to provide this date (or at least a subset of it) to users in the app
* I'm not convinced this is the right UI
* But once the data model parts of this PR are in a good place, it seems reasonable that we merge it to be a starting point to iterate the UI on.

2025-01-08 01:48 UTC, theospears commented on BeeKit/Model/Goal.swift
> +    }
You're right, I was trying to link to https://developer.apple.com/documentation/coredata/handling_different_data_types_in_core_data#3582174

Although https://developer.apple.com/documentation/foundation/valuetransformer might have been a better link

2025-01-08 10:44 UTC, krugerk commented
> I'm not convinced this is the right UI

For all of the users of the app on iOS, as is, the deltas shown basically look like they did when the users knew them from delta_text. So any user on iOS should be automatically familiar with this interface.

The MR is here as a "request for comments/feedback/suggestions/...". May its spark encourage more and may it evolve from creation til merge.

2025-01-17 10:47 UTC, krugerk commented on BeeKit/Model/Goal.swift
> +    }
done

2025-01-18 00:25 UTC, theospears requested changes
Thanks for updating this to ValueTransformer. 
The most important bit of feedback here is: Do we actually need to have all the custom coding/decoding logic, or can the swift compiler generate it for us?
https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types#2904055

2025-01-18 00:25 UTC, theospears commented on BeeSwift/GoalViewController.swift
> +        self.deltasLabel.isHidden = goal.dueByTable.entries.isEmpty
[Nit] This won't collapse the height - maybe an argument for StackView here as well. Doesn't seem like a big deal though.

2025-01-18 00:25 UTC, theospears commented on BeeKit/Model/Goal.swift
> +    @NSManaged public var dueByTable: DueByTable
I suggest calling this variable `dueBy` - I've been trying to exactly match api names (modulo casing and underscores) so I don't need to remember both.

2025-01-18 00:25 UTC, theospears commented on BeeKit/Model/DueBy/DueByTable.swift
> +            ?? [:]
Could you explain what is happening here?

2025-01-18 00:25 UTC, theospears commented on BeeKit/Model/DueBy/DueByTable.swift
> +    public static var supportsSecureCoding: Bool { true }
From: https://developer.apple.com/documentation/foundation/nssecurecoding

> An object that does override [init(coder:)](https://developer.apple.com/documentation/mapkit/mkmapitem/init(coder:)) must decode any enclosed objects using the [decodeObjectOfClass:forKey:](https://developer.apple.com/documentation/foundation/nscoder/1442558-decodeobjectofclass) method. For example:

It appears we aren't doing this, so shouldn't be returning true here?

2025-01-18 00:25 UTC, theospears commented on BeeKit/Model/DueBy/BeeminderDueByEntry.swift
> +    public func encode(with coder: NSCoder) {
Do we need all this custom encode/decode logic? My understanding is Swift (4.0+) should be able to synthesize it.

2025-01-18 18:49 UTC, krugerk commented on BeeKit/Model/DueBy/DueByTable.swift
> +    public static var supportsSecureCoding: Bool { true }
True. It seems I missed one entry.

2025-01-18 18:51 UTC, krugerk commented on BeeKit/Model/DueBy/BeeminderDueByEntry.swift
> +    public func encode(with coder: NSCoder) {
Codable can take care of some of it. The rest is for NSCoding (NSSecureCoding). We can make one use the other, though this is not available out of the box, afaik. Will look into it

2025-01-18 18:54 UTC, krugerk commented on BeeSwift/GoalViewController.swift
> +    var dueByContainsSpecificAmounts: Bool {
It is. The idea was just to show the deltas when at least one of them was a number (not just all checkmarks). I am thinking it might be better to just leave the checkmarks and thus this code remains unused and can be removed.

2025-01-18 18:54 UTC, krugerk commented on BeeSwift/AppDelegate.swift
> +        DueByTableValueTransformer.register()
Yes, this makes sense - move it to the location where the rest of core data is initialized.

2025-01-18 19:00 UTC, theospears commented on BeeKit/Model/DueBy/BeeminderDueByEntry.swift
> +    public func encode(with coder: NSCoder) {
If we are using NSSecureCoding, can we use `NSSecureUnarchiveFromDataTransformer` instead of a custom one?

2025-01-18 19:47 UTC, krugerk commented on BeeKit/Model/DueBy/BeeminderDueByEntry.swift
> +    public func encode(with coder: NSCoder) {
I do not think so. I think if custom, core data non-native, are being stored, then a custom valuetransformer is needed.

2025-01-19 09:41 UTC, krugerk commented on BeeKit/Model/DueBy/BeeminderDueByEntry.swift
> +    public func encode(with coder: NSCoder) {
> Do we need all this custom encode/decode logic?

This uses the pattern the rest of the app uses: SwiftyJSON and manually plucking out from the json.

> My understanding is Swift (4.0+) should be able to synthesize it.

NSCoding's encode: `public func encode(with coder: NSCoder)`
Codable's encode: `public func encode(to encoder: Encoder) throws`

2025-01-20 03:31 UTC, theospears commented
I put together an example of what I was thinking with regards to using Codable in #617.

2025-01-20 07:53 UTC, krugerk commented
> I put together an example of what I was thinking with regards to using Codable in #617.

OK. This merge request has been updated accordingly: removed the intermediary container that just stored the dictionary. Removed the NS(Secure)Coding of `BeeminderDueByEntry`. Used lowerCamelCase instead of snake_case.

2025-01-20 07:54 UTC, krugerk commented on BeeKit/Model/Goal.swift
> +    @NSManaged public var dueByDaystamp: DueByDictionary
```suggestion
    @NSManaged public var dueByDay: DueByDictionary
```

```suggestion
    @NSManaged public var dueByDayMap: DueByDictionary
```

```suggestion
    @NSManaged public var dueByDate: DueByDictionary
```

2025-01-20 08:17 UTC, krugerk commented on BeeSwift/GoalViewController.swift
> +        self.deltasLabel.isHidden = goal.dueByTable.entries.isEmpty
I would hope the app's UI would all be written in `SwiftUI` before long. Shall the views first be migrated to `UIKit`'s `UIStackView`?

2025-02-24 03:48 UTC, theospears approved these changes

2025-02-24 03:49 UTC, merged

2026-06-11 17:40 UTC, krugerk commented
Another suggestion was showing

> something like

> 1 safe day
> [delta for the first non-safe day]